development:
  FACEBOOK_KEY: 710765152386720
  FACEBOOK_SECRET: 93844e8574602c3e26d5e8d6c23baeee

  GOOGLE_KEY: 980735335585-qhdm49ul6ja90eh3j48qs2a26gd23bjv.apps.googleusercontent.com
  GOOGLE_SECRET: xULdupW1bJaCrGOKYyD4OIZA

  LINKEDIN_KEY: 75zjgnxikgvqgc
  LINKEDIN_SECRET: ABkfs8TJhEqREgWm